version: '3.8'

services:
  cassandra:
    image: cassandra:4.0
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=shortener-cluster
    volumes:
      - /root/.cassandra/init.cql:/docker-entrypoint-initdb.d/init.cql

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:3.4.0-debian-11-r0
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_BROKER_ID=1
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  shortener-service:
    build: ./shortener-service
    ports:
      - "8080:8080"
    environment:
      - APP_FORBIDDENWORDS=porn,sex
    depends_on:
      - cassandra
      - kafka
      - postgres

  redirect-service:
    build: ./redirect-service
    ports:
      - "8081:8081"
    depends_on:
      - cassandra

  cleaner-service:
    build: ./cleaner-service
    depends_on:
      - cassandra
    environment:
      SPRING_DATA_CASSANDRA_CONTACT_POINTS: cassandra
      SPRING_DATA_CASSANDRA_PORT: 9042
      SPRING_DATA_CASSANDRA_KEYSPACE_NAME: shortener
      SPRING_DATA_CASSANDRA_LOCAL_DATACENTER: datacenter1
      SPRING_DATA_CASSANDRA_SCHEMA_ACTION: CREATE_IF_NOT_EXISTS
      CLEANER_TTL_DAYS: 365

#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/shortener
#      SPRING_DATASOURCE_USERNAME: user
#      SPRING_DATASOURCE_PASSWORD: password

networks:
  default:
    name: shortener-net
