version: '3.8'

services:
  cassandra:
    image: cassandra:4.0
    ports:
      - "9042:9042"

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
    depends_on:
      - zookeeper

  shortener-service:
    build: ./shortener-service
    ports:
      - "8080:8080"
    depends_on:
      - cassandra
      - kafka
      - postgres

  redirect-service:
    build: ./redirect-service
    ports:
      - "8081:8081"
    depends_on:
      - cassandra

  cleaner-service:
    build: ./cleaner-service
    depends_on:
      - cassandra
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/shortener
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password

networks:
  default:
    name: shortener-net
